CREATE TABLE IF NOT EXISTS policies(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    ptype VARCHAR DEFAULT '',
    v0 VARCHAR DEFAULT '',
    v1 VARCHAR DEFAULT '',
    v2 VARCHAR DEFAULT '',
    v3 VARCHAR DEFAULT '',
    v4 VARCHAR DEFAULT '',
    v5 VARCHAR DEFAULT ''
)